import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const TopNav = () => (
  <nav className="flex justify-between border-b border-b-white p-5 text-2xl font-semibold">
    <div>Gallery</div>
    <div>Sign-In</div>
  </nav>
);

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col gap-5">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
